import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { drive_v3, docs_v1, driveactivity_v2 } from 'googleapis';
import { ensureDir, appendJsonl, writeJson } from '../fs.js';
import { slugify } from '../drive/ids.js';
import { snapshotFromText } from '../normalize.js';
import { diffSnapshots } from '../diff.js';
import type { RevisionRecord, SourceFile, Snapshot } from '../types.js';

const DOC = 'application/vnd.google-apps.document';
export async function harvestGoogleDoc(apis: { drive: drive_v3.Drive; docs: docs_v1.Docs; activity: driveactivity_v2.Driveactivity }, file: SourceFile, outRoot: string): Promise<void> {
  if (file.mimeType !== DOC) return; const root = path.join(outRoot, 'documents', `${slugify(file.name)}--${file.id}`); await ensureDir(root); await writeJson(path.join(root, 'source/file.json'), file);
  await exportCurrent(apis.drive, file.id, root); await saveDocsViews(apis.docs, file.id, root); await saveComments(apis.drive, file.id, root); await saveActivity(apis.activity, file.id, root);
  const revisions = await listRevisions(apis.drive, file.id, root); const snapshots: Snapshot[] = [];
  for (const rev of revisions) { const text = await exportRevisionText(apis.drive, file.id, rev, root); if (text) snapshots.push(snapshotFromText(file.id, rev.revisionId, text)); }
  if (snapshots.length) await writeFile(path.join(root, 'derived/normalized-snapshots.jsonl'), snapshots.map(s => JSON.stringify(s)).join('\n') + '\n');
  const events = snapshots.slice(1).flatMap((s, i) => diffSnapshots(file.name, snapshots[i], s, revisions[i + 1])); await writeFile(path.join(root, 'derived/word-events.jsonl'), events.map(e => JSON.stringify(e)).join('\n'));
  await writeFile(path.join(root, 'derived/confidence-report.md'), '# Confidence report\n\nDerived from available Google API revision evidence. Drive revisions may be merged or incomplete.\n');
}
async function exportCurrent(drive: drive_v3.Drive, fileId: string, root: string) { await ensureDir(path.join(root, 'exports')); const formats = [['current.txt','text/plain'],['current.md','text/markdown'],['current.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document'],['current.pdf','application/pdf']] as const; for (const [name,mimeType] of formats) try { const res = await drive.files.export({ fileId, mimeType }, { responseType: 'arraybuffer' }); await writeFile(path.join(root, 'exports', name), Buffer.from(res.data as ArrayBuffer)); } catch {} }
async function saveDocsViews(docs: docs_v1.Docs, fileId: string, root: string) { const views = [['current.docs-api.json', undefined],['suggestions-inline.docs.json','SUGGESTIONS_INLINE'],['suggestions-accepted.docs.json','PREVIEW_SUGGESTIONS_ACCEPTED'],['suggestions-rejected.docs.json','PREVIEW_WITHOUT_SUGGESTIONS']] as const; for (const [name, suggestionsViewMode] of views) try { const res = await docs.documents.get({ documentId: fileId, suggestionsViewMode }); await writeJson(path.join(root, 'exports', name), res.data); } catch {} }
async function saveComments(drive: drive_v3.Drive, fileId: string, root: string) { let pageToken: string | undefined; do { try { const res = await drive.comments.list({ fileId, fields: '*', pageToken }); for (const c of res.data.comments ?? []) { await appendJsonl(path.join(root, 'source/comments.jsonl'), c); for (const r of c.replies ?? []) await appendJsonl(path.join(root, 'source/replies.jsonl'), r); } pageToken = res.data.nextPageToken ?? undefined; } catch { pageToken = undefined; } } while (pageToken); }
async function saveActivity(activity: driveactivity_v2.Driveactivity, fileId: string, root: string) { try { const res = await activity.activity.query({ requestBody: { itemName: `items/${fileId}` } }); for (const a of res.data.activities ?? []) await appendJsonl(path.join(root, 'source/activity.jsonl'), a); } catch {} }
async function listRevisions(drive: drive_v3.Drive, fileId: string, root: string): Promise<RevisionRecord[]> { const revs: RevisionRecord[] = []; let pageToken: string | undefined; do { const res = await drive.revisions.list({ fileId, fields: 'nextPageToken,revisions(id,modifiedTime,lastModifyingUser,exportLinks,keepForever,originalFilename)', pageToken }); for (const r of res.data.revisions ?? []) { const rec = { fileId, revisionId: r.id!, modifiedTime: r.modifiedTime ?? undefined, lastModifyingUser: r.lastModifyingUser as any, exportLinks: r.exportLinks ?? undefined, keepForever: r.keepForever ?? undefined, originalFilename: r.originalFilename ?? undefined }; revs.push(rec); await appendJsonl(path.join(root, 'source/revisions.jsonl'), rec); await writeJson(path.join(root, 'revisions', rec.revisionId, 'revision.json'), rec); } pageToken = res.data.nextPageToken ?? undefined; } while (pageToken); return revs; }
async function exportRevisionText(drive: drive_v3.Drive, fileId: string, rev: RevisionRecord, root: string): Promise<string | undefined> { const dir = path.join(root, 'revisions', rev.revisionId); await ensureDir(dir); try { const res = await drive.revisions.get({ fileId, revisionId: rev.revisionId, alt: 'media' }, { responseType: 'arraybuffer' }); const text = Buffer.from(res.data as ArrayBuffer).toString('utf8'); await writeFile(path.join(dir, 'snapshot.txt'), text); return text; } catch { return undefined; } }
